# Generated by Django 5.0.6 on 2024-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinartag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='webinar',
            name='tags',
            field=models.ManyToManyField(to='webinar.webinartag'),
        ),
        migrations.AlterField(
            model_name='webinartag',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
        migrations.RemoveField(
            model_name='webinartag',
            name='webinar',
        ),
    ]
