# Generated by Django 5.0.6 on 2024-06-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_alter_webinartag_unique_together_webinar_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='speaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
